### ISSUE TITLE
Add an inclinometer example

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_LSM303_Accel#2]
This PR in an older lib had the good idea to add an inclinometer example:
https://github.com/adafruit/Adafruit_Python_LSM303/pull/4/files

We should add similar code to this lib

**Comment by FoamyGuy** [comment]
I've got an order that includes some of these sensors on the way to me now. Once they arrive I will work on bringing these examples into the new libraries
